baseurl = "/"
title = "Hamish Pierpont"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Hamish Pierpont"
    description = "A blog about software"
    github = "https://github.com/HamishPierpont"
    email = "pilothemi@gmail.com"
    opengraph = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"